export const questionBank = [
  // --- ENGLISH (ENG) ---
  {
    id: 1,
    subject: 'ENG',
    question: "Choose the option nearest in meaning to 'ABERRATION'.",
    options: ['Normality', 'Deviation', 'Intensity', 'Adherence'],
    correct: 1,
    explanation:
      'Aberration means a departure from what is normal or expected.',
  },
  {
    id: 2,
    subject: 'ENG',
    question: 'Identify the misspelled word:',
    options: ['Occurrence', 'Maintenance', 'Pronounciation', 'Acknowledge'],
    correct: 2,
    explanation: "The correct spelling is 'Pronunciation'.",
  },
  {
    id: 3,
    subject: 'ENG',
    question: 'The students were advised to ___ from smoking.',
    options: ['Absolve', 'Abstain', 'Abduct', 'Abhor'],
    correct: 1,
    explanation: 'To abstain is to restrain oneself from doing something.',
  },
  {
    id: 4,
    subject: 'ENG',
    question: "Choose the option opposite in meaning to 'FUTILE'.",
    options: ['Useless', 'Productive', 'Vain', 'Empty'],
    correct: 1,
    explanation: 'Futile means useless; its opposite is productive.',
  },
  {
    id: 5,
    subject: 'ENG',
    question: 'Neither the teacher nor the students ___ present.',
    options: ['Is', 'Was', 'Are', 'Has been'],
    correct: 2,
    explanation:
      "In 'neither/nor', the verb agrees with the closer subject (students).",
  },
  {
    id: 6,
    subject: 'ENG',
    question: 'He is a person ___ I know very well.',
    options: ['Who', 'Which', 'Whom', 'Whose'],
    correct: 2,
    explanation: 'Whom is used for the object of a verb.',
  },
  {
    id: 7,
    subject: 'ENG',
    question: 'I look forward to ___ you at the party.',
    options: ['See', 'Seen', 'Saw', 'Seeing'],
    correct: 3,
    explanation: "The phrase 'look forward to' is followed by a gerund (-ing).",
  },
  {
    id: 8,
    subject: 'ENG',
    question: "Which of these is a synonym for 'GIGANTIC'?",
    options: ['Tiny', 'Huge', 'Fragile', 'Swift'],
    correct: 1,
    explanation: 'Gigantic means extremely large.',
  },
  {
    id: 9,
    subject: 'ENG',
    question: 'Choose the correctly punctuated sentence.',
    options: [
      'Its a rainy day.',
      "It's a rainy day.",
      "Its' a rainy day.",
      'Its a rainy, day.',
    ],
    correct: 1,
    explanation: "It's is the contraction for 'It is'.",
  },
  {
    id: 10,
    subject: 'ENG',
    question: 'The boy is too young to ___ such a heavy load.',
    options: ['Bear', 'Bare', 'Beer', 'Bier'],
    correct: 0,
    explanation: 'To bear means to carry.',
  },

  // --- MATHEMATICS (MATH) ---
  {
    id: 11,
    subject: 'MATH',
    question: 'Solve for x: log₂(x + 4) = 3',
    options: ['2', '4', '6', '8'],
    correct: 1,
    explanation: '2³ = x + 4 => 8 = x + 4 => x = 4.',
  },
  {
    id: 12,
    subject: 'MATH',
    question: 'Find the derivative of y = 3x² + 2x + 1',
    options: ['6x + 2', '3x + 2', '6x', '6x + 1'],
    correct: 0,
    explanation: 'd/dx(3x²) = 6x, d/dx(2x) = 2.',
  },
  {
    id: 13,
    subject: 'MATH',
    question: 'What is the median of 2, 8, 4, 6, 10?',
    options: ['4', '5', '6', '8'],
    correct: 2,
    explanation: 'Ordered: 2,4,6,8,10. Median is 6.',
  },
  {
    id: 14,
    subject: 'MATH',
    question: 'Solve for x: 2x + 5 = 15',
    options: ['5', '10', '20', '2.5'],
    correct: 0,
    explanation: '2x = 10 => x = 5.',
  },
  {
    id: 15,
    subject: 'MATH',
    question: 'What is the value of (2³ × 2²)?',
    options: ['16', '32', '64', '12'],
    correct: 1,
    explanation: '2^(3+2) = 2⁵ = 32.',
  },
  {
    id: 16,
    subject: 'MATH',
    question: 'Find the area of a circle with radius 7cm (π = 22/7).',
    options: ['44cm²', '154cm²', '49cm²', '14cm²'],
    correct: 1,
    explanation: 'Area = πr² = 22/7 * 7 * 7 = 154.',
  },
  {
    id: 17,
    subject: 'MATH',
    question: 'Solve for x: x² - 5x + 6 = 0',
    options: ['2,3', '-2,-3', '1,6', '-1,-6'],
    correct: 0,
    explanation: '(x-2)(x-3)=0.',
  },
  {
    id: 18,
    subject: 'MATH',
    question: 'What is the sum of angles in a triangle?',
    options: ['90°', '180°', '270°', '360°'],
    correct: 1,
    explanation: 'The internal angles of any triangle sum to 180°.',
  },
  {
    id: 19,
    subject: 'MATH',
    question: 'Evaluate: ∫ 2x dx',
    options: ['x² + C', '2x² + C', 'x + C', '2 + C'],
    correct: 0,
    explanation: 'Integral of x is x²/2. So 2(x²/2) = x².',
  },
  {
    id: 20,
    subject: 'MATH',
    question: 'If 20% of a number is 40, what is the number?',
    options: ['80', '100', '200', '400'],
    correct: 2,
    explanation: '0.2x = 40 => x = 40/0.2 = 200.',
  },

  // --- PHYSICS (PHY) ---
  {
    id: 21,
    subject: 'PHY',
    question: 'The SI unit of magnetic flux density is:',
    options: ['Weber', 'Tesla', 'Henry', 'Farad'],
    correct: 1,
    explanation: 'Tesla is the unit for magnetic field strength/density.',
  },
  {
    id: 22,
    subject: 'PHY',
    question:
      'Calculate the distance covered by a car moving at 20m/s for 10s.',
    options: ['2m', '30m', '200m', '400m'],
    correct: 2,
    explanation: 'Distance = Speed × Time = 20 * 10 = 200m.',
  },
  {
    id: 23,
    subject: 'PHY',
    question:
      'The focal length of a concave mirror is 10cm. Radius of curvature is:',
    options: ['5cm', '10cm', '15cm', '20cm'],
    correct: 3,
    explanation: 'R = 2f.',
  },
  {
    id: 24,
    subject: 'PHY',
    question: 'Which of these is a scalar quantity?',
    options: ['Force', 'Velocity', 'Mass', 'Acceleration'],
    correct: 2,
    explanation: 'Mass has magnitude but no direction.',
  },
  {
    id: 25,
    subject: 'PHY',
    question: 'The pressure in a liquid increases with ___.',
    options: ['Volume', 'Depth', 'Surface Area', 'Color'],
    correct: 1,
    explanation: 'P = hρg (Pressure depends on depth).',
  },
  {
    id: 26,
    subject: 'PHY',
    question: 'Fundamental unit of luminous intensity is ___.',
    options: ['Mole', 'Kelvin', 'Ampere', 'Candela'],
    correct: 3,
    explanation: 'Candela (cd) is the SI unit.',
  },
  {
    id: 27,
    subject: 'PHY',
    question: 'The process of heat transfer in solids is ___.',
    options: ['Conduction', 'Convection', 'Radiation', 'Evaporation'],
    correct: 0,
    explanation: 'Conduction happens through molecular vibration in solids.',
  },
  {
    id: 28,
    subject: 'PHY',
    question: "Ohm's law relates Voltage, Current and ___.",
    options: ['Power', 'Capacitance', 'Resistance', 'Inductance'],
    correct: 2,
    explanation: 'V = IR.',
  },
  {
    id: 29,
    subject: 'PHY',
    question: 'Velocity is defined as the rate of change of ___.',
    options: ['Speed', 'Distance', 'Displacement', 'Time'],
    correct: 2,
    explanation: 'Velocity = Displacement / Time.',
  },
  {
    id: 30,
    subject: 'PHY',
    question: 'What is the speed of light in vacuum?',
    options: ['3x10⁸ m/s', '3x10⁷ m/s', '3x10⁶ m/s', '3x10⁹ m/s'],
    correct: 0,
    explanation: 'Approximately 300,000 km/s.',
  },

  // --- BIOLOGY (BIO) ---
  {
    id: 31,
    subject: 'BIO',
    question: "The 'Powerhouse' of the cell is the ___.",
    options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi Body'],
    correct: 2,
    explanation: 'Mitochondria produce ATP (energy).',
  },
  {
    id: 32,
    subject: 'BIO',
    question: 'Which organ is responsible for pumping blood?',
    options: ['Lungs', 'Brain', 'Liver', 'Heart'],
    correct: 3,
    explanation: 'The heart pumps oxygenated and deoxygenated blood.',
  },
  {
    id: 33,
    subject: 'BIO',
    question: 'Green plants are called producers because they ___.',
    options: ['Eat insects', 'Photosynthesize', 'Decompose', 'Respire'],
    correct: 1,
    explanation: 'They produce their own food using sunlight.',
  },
  {
    id: 34,
    subject: 'BIO',
    question:
      'The process of maintaining a stable internal environment is ___.',
    options: ['Osmosis', 'Homeostasis', 'Diffusion', 'Respiration'],
    correct: 1,
    explanation: 'Homeostasis keeps body conditions steady.',
  },
  {
    id: 35,
    subject: 'BIO',
    question: "Which of these is the 'Universal Donor' blood group?",
    options: ['Group A', 'Group B', 'Group AB', 'Group O'],
    correct: 3,
    explanation: 'Group O can give to all other groups.',
  },
  {
    id: 36,
    subject: 'BIO',
    question: 'The functional unit of the kidney is the ___.',
    options: ['Nephron', 'Neuron', 'Alveoli', 'Villi'],
    correct: 0,
    explanation: 'Nephrons filter the blood.',
  },
  {
    id: 37,
    subject: 'BIO',
    question: 'Mendel is known for his work on ___.',
    options: ['Evolution', 'Genetics', 'Taxonomy', 'Ecology'],
    correct: 1,
    explanation: 'He is the father of modern genetics.',
  },
  {
    id: 38,
    subject: 'BIO',
    question: 'The male reproductive part of a flower is the ___.',
    options: ['Carpel', 'Stamen', 'Petal', 'Sepal'],
    correct: 1,
    explanation: 'The stamen produces pollen.',
  },
  {
    id: 39,
    subject: 'BIO',
    question: 'Smallpox is caused by a ___.',
    options: ['Bacterium', 'Virus', 'Fungus', 'Protozoan'],
    correct: 1,
    explanation: 'It is a viral infection.',
  },
  {
    id: 40,
    subject: 'BIO',
    question: 'The sequence of amino acids forms a ___.',
    options: ['Lipid', 'Carbohydrate', 'Protein', 'Vitamin'],
    correct: 2,
    explanation: 'Proteins are polymer chains of amino acids.',
  },

  // --- CHEMISTRY (CHEM) ---
  {
    id: 41,
    subject: 'CHEM',
    question: 'What is the atomic number of Carbon?',
    options: ['6', '12', '14', '1'],
    correct: 0,
    explanation: 'Carbon is the 6th element.',
  },
  {
    id: 42,
    subject: 'CHEM',
    question: 'A solution with a pH of 2 is ___.',
    options: ['Weakly Acidic', 'Strongly Acidic', 'Neutral', 'Alkaline'],
    correct: 1,
    explanation: 'pH 1-3 is strongly acidic.',
  },
  {
    id: 43,
    subject: 'CHEM',
    question: 'The most abundant gas in the atmosphere is ___.',
    options: ['Oxygen', 'Hydrogen', 'Nitrogen', 'Argon'],
    correct: 2,
    explanation: 'Nitrogen makes up about 78% of air.',
  },
  {
    id: 44,
    subject: 'CHEM',
    question: 'The process of a solid turning directly into gas is ___.',
    options: ['Evaporation', 'Sublimation', 'Condensation', 'Freezing'],
    correct: 1,
    explanation: 'Example: Dry ice or Camphor.',
  },
  {
    id: 45,
    subject: 'CHEM',
    question: 'What is the chemical formula for Table Salt?',
    options: ['NaOH', 'HCl', 'NaCl', 'KCl'],
    correct: 2,
    explanation: 'Sodium Chloride (NaCl).',
  },
  {
    id: 46,
    subject: 'CHEM',
    question: 'Which particle has a negative charge?',
    options: ['Proton', 'Neutron', 'Electron', 'Nucleus'],
    correct: 2,
    explanation: 'Electrons orbit the nucleus and are negative.',
  },
  {
    id: 47,
    subject: 'CHEM',
    question: 'The bond formed by sharing electrons is ___.',
    options: ['Ionic', 'Covalent', 'Metallic', 'Hydrogen'],
    correct: 1,
    explanation: 'Covalent bonds involve sharing electron pairs.',
  },
  {
    id: 48,
    subject: 'CHEM',
    question: 'Which of these is a Noble Gas?',
    options: ['Oxygen', 'Chlorine', 'Neon', 'Nitrogen'],
    correct: 2,
    explanation: 'Neon is in Group 18.',
  },
  {
    id: 49,
    subject: 'CHEM',
    question: "Avogadro's constant is approximately ___.",
    options: ['6.02 x 10²³', '6.02 x 10²²', '1.6 x 10⁻¹⁹', '9.8 x 10¹'],
    correct: 0,
    explanation: 'The number of units in one mole.',
  },
  {
    id: 50,
    subject: 'CHEM',
    question: 'Isotopes have the same number of protons but different ___.',
    options: ['Electrons', 'Neutrons', 'Charge', 'Valency'],
    correct: 1,
    explanation: 'This gives them different mass numbers.',
  },
]
