// questions.ts

export const questionBank = [
  // --- ENGLISH (ENG) ---
  {
    id: 1,
    subject: 'ENG',
    question: "Choose the option nearest in meaning to 'ABERRATION'.",
    options: ['Normality', 'Deviation', 'Intensity', 'Adherence'],
    correct: 1,
    explanation:
      'Aberration means a departure from what is normal or expected.',
  },
  {
    id: 2,
    subject: 'ENG',
    question: 'Identify the misspelled word:',
    options: ['Occurrence', 'Maintenance', 'Pronounciation', 'Acknowledge'],
    correct: 2,
    explanation: "The correct spelling is 'Pronunciation'.",
  },
  {
    id: 3,
    subject: 'ENG',
    question: 'The students were advised to ___ from smoking.',
    options: ['Absolve', 'Abstain', 'Abduct', 'Abhor'],
    correct: 1,
    explanation: 'To abstain is to restrain oneself from doing something.',
  },
  {
    id: 4,
    subject: 'ENG',
    question: "Choose the option opposite in meaning to 'FUTILE'.",
    options: ['Useless', 'Productive', 'Vain', 'Empty'],
    correct: 1,
    explanation: 'Futile means useless; its opposite is productive.',
  },
  {
    id: 5,
    subject: 'ENG',
    question: 'Neither the teacher nor the students ___ present.',
    options: ['Is', 'Was', 'Are', 'Has been'],
    correct: 2,
    explanation:
      "In 'neither/nor', the verb agrees with the closer subject (students).",
  },
  {
    id: 6,
    subject: 'ENG',
    question: 'He is a person ___ I know very well.',
    options: ['Who', 'Which', 'Whom', 'Whose'],
    correct: 2,
    explanation: 'Whom is used for the object of a verb.',
  },
  {
    id: 7,
    subject: 'ENG',
    question: 'I look forward to ___ you at the party.',
    options: ['See', 'Seen', 'Saw', 'Seeing'],
    correct: 3,
    explanation: "The phrase 'look forward to' is followed by a gerund (-ing).",
  },
  {
    id: 8,
    subject: 'ENG',
    question: "Which of these is a synonym for 'GIGANTIC'?",
    options: ['Tiny', 'Huge', 'Fragile', 'Swift'],
    correct: 1,
    explanation: 'Gigantic means extremely large.',
  },
  {
    id: 9,
    subject: 'ENG',
    question: 'Choose the correctly punctuated sentence.',
    options: [
      'Its a rainy day.',
      "It's a rainy day.",
      "Its' a rainy day.",
      'Its a rainy, day.',
    ],
    correct: 1,
    explanation: "It's is the contraction for 'It is'.",
  },
  {
    id: 10,
    subject: 'ENG',
    question: 'The boy is too young to ___ such a heavy load.',
    options: ['Bear', 'Bare', 'Beer', 'Bier'],
    correct: 0,
    explanation: 'To bear means to carry.',
  },
  {
    id: 51,
    subject: 'ENG',
    question: "Choose the option nearest in meaning to 'METICULOUS'.",
    options: ['Careless', 'Lazy', 'Detailed', 'Messy'],
    correct: 2,
    explanation:
      'Meticulous means showing great attention to detail; very careful and precise.',
  },
  {
    id: 52,
    subject: 'ENG',
    question: "The idiom 'a piece of cake' means:",
    options: [
      'Very difficult',
      'Something delicious',
      'Very easy',
      'A celebration',
    ],
    correct: 2,
    explanation:
      "The idiom 'a piece of cake' refers to a task that is very simple to accomplish.",
  },
  {
    id: 53,
    subject: 'ENG',
    question:
      "Identify the figure of speech: 'The wind whispered through the trees.'",
    options: ['Metaphor', 'Simile', 'Personification', 'Oxymoron'],
    correct: 2,
    explanation: 'Personification gives human qualities to non-human things.',
  },
  {
    id: 54,
    subject: 'ENG',
    question: "Choose the option opposite in meaning to 'AMBIGUOUS'.",
    options: ['Vague', 'Unclear', 'Precise', 'Doubtful'],
    correct: 2,
    explanation:
      'Ambiguous means having a double meaning; its opposite is precise or clear.',
  },
  {
    id: 55,
    subject: 'ENG',
    question: 'The plane took ___ despite the heavy rain.',
    options: ['In', 'Out', 'Off', 'On'],
    correct: 2,
    explanation:
      'To "take off" is the phrasal verb used for an aircraft leaving the ground.',
  },
  {
    id: 56,
    subject: 'ENG',
    question: 'Choose the correct collective noun: A ___ of lions.',
    options: ['Pack', 'Pride', 'Flock', 'Herd'],
    correct: 1,
    explanation: 'A group of lions is called a pride.',
  },
  {
    id: 57,
    subject: 'ENG',
    question: 'She is the ___ of the two sisters.',
    options: ['Tallest', 'Tall', 'Taller', 'More tall'],
    correct: 2,
    explanation:
      'When comparing two people, the comparative degree (taller) is used.',
  },
  {
    id: 58,
    subject: 'ENG',
    question: 'If I ___ you, I would take the offer.',
    options: ['Am', 'Was', 'Were', 'Be'],
    correct: 2,
    explanation:
      'In a conditional sentence (subjunctive mood), "were" is used regardless of the subject.',
  },
  {
    id: 59,
    subject: 'ENG',
    question: "What is the synonym of 'FRAGILE'?",
    options: ['Strong', 'Delicate', 'Durable', 'Heavy'],
    correct: 1,
    explanation: 'Fragile and delicate both mean easily broken.',
  },
  {
    id: 60,
    subject: 'ENG',
    question: 'The book ___ on the table for three days.',
    options: ['Lied', 'Lain', 'Has lain', 'Lay'],
    correct: 2,
    explanation:
      '"Has lain" is the present perfect form of the intransitive verb "to lie".',
  },

  // --- MATHEMATICS (MATH) ---
  {
    id: 11,
    subject: 'MATH',
    question: 'Solve for x: log₂(x + 4) = 3',
    options: ['2', '4', '6', '8'],
    correct: 1,
    explanation: '2³ = x + 4 => 8 = x + 4 => x = 4.',
  },
  {
    id: 12,
    subject: 'MATH',
    question: 'Find the derivative of y = 3x² + 2x + 1',
    options: ['6x + 2', '3x + 2', '6x', '6x + 1'],
    correct: 0,
    explanation: 'd/dx(3x²) = 6x, d/dx(2x) = 2.',
  },
  {
    id: 13,
    subject: 'MATH',
    question: 'What is the median of 2, 8, 4, 6, 10?',
    options: ['4', '5', '6', '8'],
    correct: 2,
    explanation: 'Ordered: 2,4,6,8,10. Median is 6.',
  },
  {
    id: 14,
    subject: 'MATH',
    question: 'Solve for x: 2x + 5 = 15',
    options: ['5', '10', '20', '2.5'],
    correct: 0,
    explanation: '2x = 10 => x = 5.',
  },
  {
    id: 15,
    subject: 'MATH',
    question: 'What is the value of (2³ × 2²)?',
    options: ['16', '32', '64', '12'],
    correct: 1,
    explanation: '2^(3+2) = 2⁵ = 32.',
  },
  {
    id: 16,
    subject: 'MATH',
    question: 'Find the area of a circle with radius 7cm (π = 22/7).',
    options: ['44cm²', '154cm²', '49cm²', '14cm²'],
    correct: 1,
    explanation: 'Area = πr² = 22/7 * 7 * 7 = 154.',
  },
  {
    id: 17,
    subject: 'MATH',
    question: 'Solve for x: x² - 5x + 6 = 0',
    options: ['2,3', '-2,-3', '1,6', '-1,-6'],
    correct: 0,
    explanation: '(x-2)(x-3)=0.',
  },
  {
    id: 18,
    subject: 'MATH',
    question: 'What is the sum of angles in a triangle?',
    options: ['90°', '180°', '270°', '360°'],
    correct: 1,
    explanation: 'The internal angles of any triangle sum to 180°.',
  },
  {
    id: 19,
    subject: 'MATH',
    question: 'Evaluate: ∫ 2x dx',
    options: ['x² + C', '2x² + C', 'x + C', '2 + C'],
    correct: 0,
    explanation: 'Integral of x is x²/2. So 2(x²/2) = x².',
  },
  {
    id: 20,
    subject: 'MATH',
    question: 'If 20% of a number is 40, what is the number?',
    options: ['80', '100', '200', '400'],
    correct: 2,
    explanation: '0.2x = 40 => x = 40/0.2 = 200.',
  },
  {
    id: 61,
    subject: 'MATH',
    question: 'What is the slope of the line y = 4x - 7?',
    options: ['-7', '4', '7', '1/4'],
    correct: 1,
    explanation: 'In y=mx+b, m is the slope.',
  },
  {
    id: 62,
    subject: 'MATH',
    question: 'Find the value of x if 3^(x-1) = 27.',
    options: ['2', '3', '4', '5'],
    correct: 2,
    explanation: '3^(x-1) = 3³ => x-1 = 3 => x = 4.',
  },
  {
    id: 63,
    subject: 'MATH',
    question:
      'Calculate the simple interest on $1000 at 5% per annum for 3 years.',
    options: ['$150', '$50', '$1150', '$300'],
    correct: 0,
    explanation: 'I = PRT/100 = 1000 * 5 * 3 / 100 = 150.',
  },
  {
    id: 64,
    subject: 'MATH',
    question: 'What is the value of sin(90°)?',
    options: ['0', '0.5', '1', 'Undefined'],
    correct: 2,
    explanation: 'The sine of 90 degrees is exactly 1.',
  },
  {
    id: 65,
    subject: 'MATH',
    question: 'A polygon with 8 sides is called a/an:',
    options: ['Hexagon', 'Heptagon', 'Octagon', 'Nonagon'],
    correct: 2,
    explanation: 'An octagon has eight sides.',
  },
  {
    id: 66,
    subject: 'MATH',
    question: 'If f(x) = x² + 2x, find f(3).',
    options: ['12', '15', '9', '21'],
    correct: 1,
    explanation: 'f(3) = 3² + 2(3) = 9 + 6 = 15.',
  },
  {
    id: 67,
    subject: 'MATH',
    question: 'Convert 120° to radians.',
    options: ['π/3', '2π/3', '3π/4', 'π/2'],
    correct: 1,
    explanation: '120 * (π/180) = 2π/3.',
  },
  {
    id: 68,
    subject: 'MATH',
    question: 'How many subsets does a set with 4 elements have?',
    options: ['8', '12', '16', '32'],
    correct: 2,
    explanation: 'Number of subsets = 2ⁿ. Here 2⁴ = 16.',
  },
  {
    id: 69,
    subject: 'MATH',
    question: 'Solve for x: √(x + 5) = 4',
    options: ['9', '11', '16', '21'],
    correct: 1,
    explanation: 'x + 5 = 16 => x = 11.',
  },
  {
    id: 70,
    subject: 'MATH',
    question: 'What is the mode of 3, 5, 3, 7, 8, 5, 3?',
    options: ['3', '5', '7', '8'],
    correct: 0,
    explanation: 'The number 3 appears most frequently (3 times).',
  },

  // --- PHYSICS (PHY) ---
  {
    id: 21,
    subject: 'PHY',
    question: 'The SI unit of magnetic flux density is:',
    options: ['Weber', 'Tesla', 'Henry', 'Farad'],
    correct: 1,
    explanation: 'Tesla is the unit for magnetic field strength/density.',
  },
  {
    id: 22,
    subject: 'PHY',
    question:
      'Calculate the distance covered by a car moving at 20m/s for 10s.',
    options: ['2m', '30m', '200m', '400m'],
    correct: 2,
    explanation: 'Distance = Speed × Time = 20 * 10 = 200m.',
  },
  {
    id: 23,
    subject: 'PHY',
    question:
      'The focal length of a concave mirror is 10cm. Radius of curvature is:',
    options: ['5cm', '10cm', '15cm', '20cm'],
    correct: 3,
    explanation: 'R = 2f.',
  },
  {
    id: 24,
    subject: 'PHY',
    question: 'Which of these is a scalar quantity?',
    options: ['Force', 'Velocity', 'Mass', 'Acceleration'],
    correct: 2,
    explanation: 'Mass has magnitude but no direction.',
  },
  {
    id: 25,
    subject: 'PHY',
    question: 'The pressure in a liquid increases with ___.',
    options: ['Volume', 'Depth', 'Surface Area', 'Color'],
    correct: 1,
    explanation: 'P = hρg (Pressure depends on depth).',
  },
  {
    id: 26,
    subject: 'PHY',
    question: 'Fundamental unit of luminous intensity is ___.',
    options: ['Mole', 'Kelvin', 'Ampere', 'Candela'],
    correct: 3,
    explanation: 'Candela (cd) is the SI unit.',
  },
  {
    id: 27,
    subject: 'PHY',
    question: 'The process of heat transfer in solids is ___.',
    options: ['Conduction', 'Convection', 'Radiation', 'Evaporation'],
    correct: 0,
    explanation: 'Conduction happens through molecular vibration in solids.',
  },
  {
    id: 28,
    subject: 'PHY',
    question: "Ohm's law relates Voltage, Current and ___.",
    options: ['Power', 'Capacitance', 'Resistance', 'Inductance'],
    correct: 2,
    explanation: 'V = IR.',
  },
  {
    id: 29,
    subject: 'PHY',
    question: 'Velocity is defined as the rate of change of ___.',
    options: ['Speed', 'Distance', 'Displacement', 'Time'],
    correct: 2,
    explanation: 'Velocity = Displacement / Time.',
  },
  {
    id: 30,
    subject: 'PHY',
    question: 'What is the speed of light in vacuum?',
    options: ['3x10⁸ m/s', '3x10⁷ m/s', '3x10⁶ m/s', '3x10⁹ m/s'],
    correct: 0,
    explanation: 'Approximately 300,000 km/s.',
  },
  {
    id: 71,
    subject: 'PHY',
    question: 'The rate of work done is called:',
    options: ['Force', 'Energy', 'Power', 'Momentum'],
    correct: 2,
    explanation: 'Power = Work / Time.',
  },
  {
    id: 72,
    subject: 'PHY',
    question: 'The escape velocity of Earth is approximately:',
    options: ['1.1 km/s', '11.2 km/s', '5.5 km/s', '20 km/s'],
    correct: 1,
    explanation:
      'It is the minimum speed needed to break free from Earth gravity.',
  },
  {
    id: 73,
    subject: 'PHY',
    question: "Newton's First Law is also known as the Law of:",
    options: ['Acceleration', 'Inertia', 'Action-Reaction', 'Gravity'],
    correct: 1,
    explanation:
      'An object remains at rest unless acted upon by an external force.',
  },
  {
    id: 74,
    subject: 'PHY',
    question: 'Which instrument measures atmospheric pressure?',
    options: ['Thermometer', 'Hygrometer', 'Barometer', 'Anemometer'],
    correct: 2,
    explanation: 'A barometer is used to measure air pressure.',
  },
  {
    id: 75,
    subject: 'PHY',
    question: 'Sound waves are ___ waves.',
    options: [
      'Transverse',
      'Longitudinal',
      'Electromagnetic',
      'Non-mechanical',
    ],
    correct: 1,
    explanation:
      'Sound requires a medium and moves as compressions and rarefactions.',
  },
  {
    id: 76,
    subject: 'PHY',
    question: 'The energy possessed by a body due to its motion is:',
    options: ['Potential', 'Kinetic', 'Chemical', 'Nuclear'],
    correct: 1,
    explanation: 'Kinetic Energy = 1/2 mv².',
  },
  {
    id: 77,
    subject: 'PHY',
    question:
      'The colors in a rainbow are produced by light ___ in water drops.',
    options: ['Reflection', 'Refraction', 'Dispersion', 'Diffraction'],
    correct: 2,
    explanation:
      'Dispersion is the splitting of white light into its component colors.',
  },
  {
    id: 78,
    subject: 'PHY',
    question:
      'A device that converts mechanical energy into electrical energy is:',
    options: ['Motor', 'Generator', 'Transformer', 'Battery'],
    correct: 1,
    explanation: 'An electric generator (dynamo) performs this conversion.',
  },
  {
    id: 79,
    subject: 'PHY',
    question: 'Specific heat capacity is measured in:',
    options: ['J/kg', 'J/K', 'J/kg·K', 'Watts'],
    correct: 2,
    explanation:
      'The amount of heat required to raise 1kg of a substance by 1 Kelvin.',
  },
  {
    id: 80,
    subject: 'PHY',
    question:
      'What type of lens is used to correct Myopia (Short-sightedness)?',
    options: ['Convex', 'Biconvex', 'Concave', 'Cylindrical'],
    correct: 2,
    explanation:
      'A diverging (concave) lens is needed to push the focal point back to the retina.',
  },

  // --- BIOLOGY (BIO) ---
  {
    id: 31,
    subject: 'BIO',
    question: "The 'Powerhouse' of the cell is the ___.",
    options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi Body'],
    correct: 2,
    explanation: 'Mitochondria produce ATP (energy).',
  },
  {
    id: 32,
    subject: 'BIO',
    question: 'Which organ is responsible for pumping blood?',
    options: ['Lungs', 'Brain', 'Liver', 'Heart'],
    correct: 3,
    explanation: 'The heart pumps oxygenated and deoxygenated blood.',
  },
  {
    id: 33,
    subject: 'BIO',
    question: 'Green plants are called producers because they ___.',
    options: ['Eat insects', 'Photosynthesize', 'Decompose', 'Respire'],
    correct: 1,
    explanation: 'They produce their own food using sunlight.',
  },
  {
    id: 34,
    subject: 'BIO',
    question:
      'The process of maintaining a stable internal environment is ___.',
    options: ['Osmosis', 'Homeostasis', 'Diffusion', 'Respiration'],
    correct: 1,
    explanation: 'Homeostasis keeps body conditions steady.',
  },
  {
    id: 35,
    subject: 'BIO',
    question: "Which of these is the 'Universal Donor' blood group?",
    options: ['Group A', 'Group B', 'Group AB', 'Group O'],
    correct: 3,
    explanation: 'Group O can give to all other groups.',
  },
  {
    id: 36,
    subject: 'BIO',
    question: 'The functional unit of the kidney is the ___.',
    options: ['Nephron', 'Neuron', 'Alveoli', 'Villi'],
    correct: 0,
    explanation: 'Nephrons filter the blood.',
  },
  {
    id: 37,
    subject: 'BIO',
    question: 'Mendel is known for his work on ___.',
    options: ['Evolution', 'Genetics', 'Taxonomy', 'Ecology'],
    correct: 1,
    explanation: 'He is the father of modern genetics.',
  },
  {
    id: 38,
    subject: 'BIO',
    question: 'The male reproductive part of a flower is the ___.',
    options: ['Carpel', 'Stamen', 'Petal', 'Sepal'],
    correct: 1,
    explanation: 'The stamen produces pollen.',
  },
  {
    id: 39,
    subject: 'BIO',
    question: 'Smallpox is caused by a ___.',
    options: ['Bacterium', 'Virus', 'Fungus', 'Protozoan'],
    correct: 1,
    explanation: 'It is a viral infection.',
  },
  {
    id: 40,
    subject: 'BIO',
    question: 'The sequence of amino acids forms a ___.',
    options: ['Lipid', 'Carbohydrate', 'Protein', 'Vitamin'],
    correct: 2,
    explanation: 'Proteins are polymer chains of amino acids.',
  },
  {
    id: 81,
    subject: 'BIO',
    question: 'The red pigment in blood that carries oxygen is:',
    options: ['Plasma', 'Hemoglobin', 'Chlorophyll', 'Platelet'],
    correct: 1,
    explanation: 'Hemoglobin binds with oxygen in red blood cells.',
  },
  {
    id: 82,
    subject: 'BIO',
    question: 'What is the largest organ in the human body?',
    options: ['Liver', 'Brain', 'Skin', 'Large Intestine'],
    correct: 2,
    explanation: 'The skin is considered the largest organ system.',
  },
  {
    id: 83,
    subject: 'BIO',
    question: 'The double-helix structure of DNA was discovered by:',
    options: ['Darwin', 'Watson and Crick', 'Pasteur', 'Fleming'],
    correct: 1,
    explanation: 'James Watson and Francis Crick proposed the model in 1953.',
  },
  {
    id: 84,
    subject: 'BIO',
    question: 'Which vitamin is synthesized by the skin in sunlight?',
    options: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'],
    correct: 3,
    explanation: 'Ultraviolet rays trigger the synthesis of Vitamin D.',
  },
  {
    id: 85,
    subject: 'BIO',
    question: 'The movement of water through a semi-permeable membrane is:',
    options: ['Diffusion', 'Osmosis', 'Active Transport', 'Transpiration'],
    correct: 1,
    explanation: 'Osmosis is the specific movement of water molecules.',
  },
  {
    id: 86,
    subject: 'BIO',
    question: 'Insects breathe through tiny holes called:',
    options: ['Gills', 'Lungs', 'Spiracles', 'Pores'],
    correct: 2,
    explanation: 'Spiracles lead to a network of tracheal tubes.',
  },
  {
    id: 87,
    subject: 'BIO',
    question: 'Which part of the brain controls balance and coordination?',
    options: ['Cerebrum', 'Cerebellum', 'Medulla', 'Hypothalamus'],
    correct: 1,
    explanation: 'The cerebellum is located at the back of the brain.',
  },
  {
    id: 88,
    subject: 'BIO',
    question: 'The first antibiotic discovered was:',
    options: ['Aspirin', 'Insulin', 'Penicillin', 'Streptomycin'],
    correct: 2,
    explanation: 'Alexander Fleming discovered Penicillin in 1928.',
  },
  {
    id: 89,
    subject: 'BIO',
    question: 'Animals that eat both plants and meat are:',
    options: ['Herbivores', 'Carnivores', 'Omnivores', 'Detritivores'],
    correct: 2,
    explanation: 'Omnivores have a mixed diet.',
  },
  {
    id: 90,
    subject: 'BIO',
    question: 'What is the master gland of the endocrine system?',
    options: ['Thyroid', 'Adrenal', 'Pituitary', 'Pancreas'],
    correct: 2,
    explanation: 'The pituitary gland regulates other endocrine glands.',
  },

  // --- CHEMISTRY (CHEM) ---
  {
    id: 41,
    subject: 'CHEM',
    question: 'What is the atomic number of Carbon?',
    options: ['6', '12', '14', '1'],
    correct: 0,
    explanation: 'Carbon is the 6th element.',
  },
  {
    id: 42,
    subject: 'CHEM',
    question: 'A solution with a pH of 2 is ___.',
    options: ['Weakly Acidic', 'Strongly Acidic', 'Neutral', 'Alkaline'],
    correct: 1,
    explanation: 'pH 1-3 is strongly acidic.',
  },
  {
    id: 43,
    subject: 'CHEM',
    question: 'The most abundant gas in the atmosphere is ___.',
    options: ['Oxygen', 'Hydrogen', 'Nitrogen', 'Argon'],
    correct: 2,
    explanation: 'Nitrogen makes up about 78% of air.',
  },
  {
    id: 44,
    subject: 'CHEM',
    question: 'The process of a solid turning directly into gas is ___.',
    options: ['Evaporation', 'Sublimation', 'Condensation', 'Freezing'],
    correct: 1,
    explanation: 'Example: Dry ice or Camphor.',
  },
  {
    id: 45,
    subject: 'CHEM',
    question: 'What is the chemical formula for Table Salt?',
    options: ['NaOH', 'HCl', 'NaCl', 'KCl'],
    correct: 2,
    explanation: 'Sodium Chloride (NaCl).',
  },
  {
    id: 46,
    subject: 'CHEM',
    question: 'Which particle has a negative charge?',
    options: ['Proton', 'Neutron', 'Electron', 'Nucleus'],
    correct: 2,
    explanation: 'Electrons orbit the nucleus and are negative.',
  },
  {
    id: 47,
    subject: 'CHEM',
    question: 'The bond formed by sharing electrons is ___.',
    options: ['Ionic', 'Covalent', 'Metallic', 'Hydrogen'],
    correct: 1,
    explanation: 'Covalent bonds involve sharing electron pairs.',
  },
  {
    id: 48,
    subject: 'CHEM',
    question: 'Which of these is a Noble Gas?',
    options: ['Oxygen', 'Chlorine', 'Neon', 'Nitrogen'],
    correct: 2,
    explanation: 'Neon is in Group 18.',
  },
  {
    id: 49,
    subject: 'CHEM',
    question: "Avogadro's constant is approximately ___.",
    options: ['6.02 x 10²³', '6.02 x 10²²', '1.6 x 10⁻¹⁹', '9.8 x 10¹'],
    correct: 0,
    explanation: 'The number of units in one mole.',
  },
  {
    id: 50,
    subject: 'CHEM',
    question: 'Isotopes have the same number of protons but different ___.',
    options: ['Electrons', 'Neutrons', 'Charge', 'Valency'],
    correct: 1,
    explanation: 'This gives them different mass numbers.',
  },
  {
    id: 91,
    subject: 'CHEM',
    question: 'What is the most reactive metal in the reactivity series?',
    options: ['Gold', 'Iron', 'Potassium', 'Calcium'],
    correct: 2,
    explanation: 'Potassium reacts violently even with cold water.',
  },
  {
    id: 92,
    subject: 'CHEM',
    question: 'The common name for Sodium Bicarbonate is:',
    options: [
      'Baking Soda',
      'Caustic Soda',
      'Bleaching Powder',
      'Washing Soda',
    ],
    correct: 0,
    explanation: 'NaHCO3 is used in baking to make dough rise.',
  },
  {
    id: 93,
    subject: 'CHEM',
    question: 'Which gas is produced when an acid reacts with a metal?',
    options: ['Oxygen', 'Hydrogen', 'Carbon dioxide', 'Chlorine'],
    correct: 1,
    explanation: 'Metal + Acid -> Salt + Hydrogen gas.',
  },
  {
    id: 94,
    subject: 'CHEM',
    question: 'The vertical columns in the Periodic Table are called:',
    options: ['Periods', 'Groups', 'Rows', 'Levels'],
    correct: 1,
    explanation: 'There are 18 groups in the standard periodic table.',
  },
  {
    id: 95,
    subject: 'CHEM',
    question: 'Which of these is an example of a chemical change?',
    options: [
      'Melting ice',
      'Boiling water',
      'Rusting of iron',
      'Breaking glass',
    ],
    correct: 2,
    explanation: 'Rusting creates a new substance (iron oxide).',
  },
  {
    id: 96,
    subject: 'CHEM',
    question: 'What is the hardest natural substance known?',
    options: ['Gold', 'Iron', 'Diamond', 'Graphite'],
    correct: 2,
    explanation: 'Diamond is an allotrope of carbon with a rigid structure.',
  },
  {
    id: 97,
    subject: 'CHEM',
    question: 'The pH of pure water is approximately:',
    options: ['0', '5', '7', '14'],
    correct: 2,
    explanation: 'Pure water is neutral.',
  },
  {
    id: 98,
    subject: 'CHEM',
    question: 'A catalyst is a substance that ___ a chemical reaction.',
    options: ['Stops', 'Slows down', 'Speeds up', 'Changes the color of'],
    correct: 2,
    explanation:
      'Catalysts lower the activation energy without being consumed.',
  },
  {
    id: 99,
    subject: 'CHEM',
    question: 'The loss of electrons is called:',
    options: ['Reduction', 'Oxidation', 'Hydration', 'Sublimation'],
    correct: 1,
    explanation: 'OIL RIG: Oxidation Is Loss, Reduction Is Gain.',
  },
  {
    id: 100,
    subject: 'CHEM',
    question: 'What is the chemical formula for Methane?',
    options: ['CH4', 'C2H6', 'CO2', 'NH3'],
    correct: 0,
    explanation: 'Methane is the simplest alkane.',
  },
]
